# Build stage
FROM rust:1.65 as builder
WORKDIR /app
COPY . .
RUN cargo build --release

# Runtime stage
FROM debian:buster-slim
WORKDIR /app
COPY --from=builder /app/target/release/lms_api_gateway_s3 .
EXPOSE 8080
ENTRYPOINT ["./lms_api_gateway_s3"]
